package rs3.unpack.script;

import rs3.unpack.Type;

import java.util.List;

import static rs3.unpack.Type.*;

public enum JavaScriptCommand {
    REQUEST_PROFANITY_FILTER_RESULT(1, List.of(BOOLEAN)),
    SET_LAST_JOINED_CHAT_REPLY(2, List.of(STRING)),
    IS_MUTED_REPLY(3, List.of(BOOLEAN)),
    FRIEND_CHAT_NAME_REPLY(4, List.of(STRING)),
    FRIEND_MIN_ENTER_RANK_REPLY(5, List.of(INT)),
    FRIEND_MIN_TALK_RANK_REPLY(6, List.of(INT)),
    FRIEND_MIN_KICK_RANK_REPLY(7, List.of(INT)),
    GET_CLAN_STATUS(8, List.of(BOOLEAN, BOOLEAN)),
    REQUEST_ALL_CHAT_FILTERS_REPLY(9, List.of(INT, INT, INT)),
    REQUEST_PRIVATE_CHAT_FILTER_REPLY(10, List.of(INT)),
    REQUEST_FRIEND_CHAT_FILTER_REPLY(11, List.of(INT)),
    REQUEST_CLAN_CHAT_FILTER_REPLY(12, List.of(INT)),
    GET_CHAT_CROWN_IMAGE_ID_REPLY(13, List.of(INT)),
    REQUEST_GE_SINGLE_SLOT_REPLY(14, List.of(INT, OBJ, STRING, STRING, INT, INT, INT, INT, INT, INT, INT, BOOLEAN, OBJ, INT, OBJ, INT)),
    GE_UPDATE_NOTIFICATION(15, List.of(INT, INT, INT)),
    IS_TRADE_RESTRICTED_REPLY(16, List.of(BOOLEAN)),
    REQUEST_DDS_LIST_ITEM_REPLY(17, List.of(INT, STRING, INT, INT, INT, BOOLEAN, INT)),
    REQUEST_DD_INFO_REPLY(18, List.of(BOOLEAN, INT, STRING, INT, INT, INT, BOOLEAN, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING)),
    REQUEST_BANK_TABS_REPLY(19, List.of(INT, INT, INT, INT, INT, INT, INT, INT, STRING, STRING, STRING, STRING, STRING, STRING, STRING, STRING, INT, INT)),
    REQUEST_BANK_SLOT_REPLY(20, List.of(INT, OBJ, STRING, INT, BOOLEAN, BOOLEAN, INT)),
    SET_BANK_DETAILS(21, List.of(INV, INT, INV)),
    REQUEST_BANK_SEARCH_REPLY(22, List.of(INT, OBJ, INT, INT)),
    GET_ITEM_DETAILS_REPLY(23, List.of(OBJ, STRING, STRING, INT, BOOLEAN, BOOLEAN, INT, BOOLEAN)),
    MAKE_BUY_OFFER_REPLY(24, List.of(BOOLEAN, INT)),
    MAKE_SELL_OFFER_REPLY(25, List.of(BOOLEAN, INT)),
    MESSAGE_REPLY(26, List.of(INT, STRING)),
    ABORT_OFFER_REPLY(27, List.of(BOOLEAN)),
    COLLECT_SLOT_REPLY(28, List.of()),
    PIN_ENTERED_REPLY(29, List.of(BOOLEAN, STRING, INT, BOOLEAN, INT)),
    PIN_STATUS_REPLY(30, List.of(BOOLEAN, INT, INT, INT)),
    REQUEST_GE_HISTORY_REPLY(31, List.of(OBJ, INT, INT, STRING, INT, BOOLEAN, OBJ, INT, INT, STRING, INT, BOOLEAN, OBJ, INT, INT, STRING, INT, BOOLEAN, OBJ, INT, INT, STRING, INT, BOOLEAN, OBJ, INT, INT, STRING, INT, BOOLEAN)),
    REQUEST_GE_COMPLETED_TRANSACTION_COUNT_REPLY(32, List.of(INT)),
    IS_2_FACTOR_AUTH_ENABLED_REPLY(33, List.of(BOOLEAN)),
    IS_COMAPP_TRADING_ENABLED_REPLY(34, List.of(BOOLEAN)),
    CAN_ACCESS_GE_BUY_SELL_REPLY(35, List.of(BOOLEAN));

    public final int id;
    public final List<Type> params;

    JavaScriptCommand(int id, List<Type> params) {
        this.id = id;
        this.params = params;
    }

    public static JavaScriptCommand byID(int id) {
        for (var value : values()) {
            if (value.id == id) {
                return value;
            }
        }

        throw new IllegalArgumentException("id " + id);
    }
}
